### ISSUE TITLE
Edit Page for trips

### ISSUE THREAD

**Issue by J-Massmann** [J-Massmann/capstone-project#10]
## Value Proposition
**As a** user
**I want to** be able to change the data of a trip
**in order to** be more flexible in planing my trip and e.g. to add more locations

## Description
The data of the state 'destinations' will be saved in the local storage including new data from users through the form.

## Acceptance Criteria
- [ ] New added trips are displayed after a reload and reopening the browser
- [ ] Error-message is shown if the data couldn't be loaded from the local storage

## Tasks
- [ ] Add local storage
- [ ] Add to App
- [ ] Check UI on mobile phone
