### ISSUE TITLE
Delete Trips

### ISSUE THREAD

**Issue by J-Massmann** [J-Massmann/capstone-project#11]
## Value Proposition
**As a** user
**I want to** be able to delete a trip
**in order to** be more flexible in planing my trip and e.g. cancel trips

## Description
![7_User_Story_Edit_page](https://user-images.githubusercontent.com/90213877/158153381-dff7d4e6-ae27-48ff-9f3c-33278b0938e2.png)

## Acceptance Criteria
- [ ] Delete alert message will appear by clicking the Bin-Button
- [ ] Trip will be deleted if 'Yes' is clicked
   - [ ] User will be navigated back in browser history
- [ ] User will stay on the page if "No" is clicked 

## Tasks
- [ ] Update new Page/ Edit-Page
- [ ] Add to App
- [ ] Check UI on mobile phone
