### ISSUE TITLE
Start- and End-Date

### ISSUE THREAD

**Issue by J-Massmann** [J-Massmann/capstone-project#18]
## Value Proposition
**As a** user
**I want to** set an exact date for my trip
**in order to** have a better overview of my trips

## Description
![9_User_Story_Date](https://user-images.githubusercontent.com/90213877/158859567-151b62c7-0fea-4825-80e5-5bc8480be592.png)

## Acceptance Criteria
- [x] Start- and End-Date is shown in TripCard
    - [x] TripCards a sorted by the Start-Date (future and past Trips)
- [x] Start- and End-Date is shown
    - [x] Detailspage
    - [x] Editpage
        - [x] a calender is shown when the user clicks inside the start- or end-input
    - [x] Formpage
       - [x]  a calender is shown when the user clicks inside the start- or end-input 

## Tasks
- [x] Update Component/ TripCard
- [x] Update Component/ FormEditTrip
- [x] Update Component/ FormAddTrip
- [x] Update Page / DetailTrip
- [x] Check accessibility 
- [x] Add to App
- [x] Check UI on mobile phone
