### ISSUE TITLE
Add API for destinations and locations

### ISSUE THREAD

**Issue by J-Massmann** [J-Massmann/capstone-project#19]
## Value Proposition
**As a** user
**I want to** have a searchbar incl. auto-suggestions in a form
**in order to** go to real places

## Description
The input fields for the destination and locations will be replaced by a searchbar (API) for destinations (cities and countries) and for locations (e.g. sights). This allows me to use a map in the following user stories.

## Acceptance Criteria
- [x] a user gets auto-suggestions by typing in the destination searchbar
    - [x] the chosen destination will be saved
    - [x] a user can't choose a destinations which is not auto-suggested by the API
    - [x] user gets an error message if no destination is found by the API
- [x] a user get auto-suggestions for locations (searchbar)
    - [x] the chosen location will be saved
    - [x] a user can't choose a location which is not auto-suggested by the API
    - [x] user gets an error message if no location is found by the API
 
## Tasks
- [x] Update Component/ FormEditTrip
- [x] Update Component/ FormAddTrip
- [x] add a fetch
   - [x] for destination
   - [x] for locations
- [x] Check accessibility 
- [x] Add to App
- [x] Check UI on mobile phone
