### ISSUE TITLE
Toggle bar for future and past trips

### ISSUE THREAD

**Issue by J-Massmann** [J-Massmann/capstone-project#2]
## Value Proposition
**As a** reader
**I want to** toggle between current and past trips
**in order to** sort the trips

## Description
<img height="500" src="https://user-images.githubusercontent.com/90213877/156557643-b2558320-89b2-406f-bcae-d08684ebb4f3.png" />

## Acceptance Criteria
- [ ] ToggleButtons should toggle with different color
   - [ ] Click on button sets 'aria-disabled' from the clicked button to 'true' and from the other button to 'false'
- [ ] Empty state:
   - [ ] The user can still switch between the pages
   - [ ] Empty pages should show pages 2 (Description)
- [ ] If a card is toggled, it should stay on the page until the user switches to the other page
    - [ ] Border of the TripCard is dashed

## Tasks

- [ ] Create component/ToggleButtons
    - [ ] Tests
    - [ ] Storybook 
- [ ] update component/TripCard
    - [ ] Tests
    - [ ] Storybook
- [ ] create empty-state for both pages
- [ ] add to app
    - [ ] add React Router
- [ ] Check accessibility
- [ ] Check UI on mobile phone
