### ISSUE TITLE
Add planing Routes

### ISSUE THREAD

**Issue by J-Massmann** [J-Massmann/capstone-project#20]
## Value Proposition
**As a** user
**I want to** plan different Routes for each day
**in order to** have a better holiday experience / plan

## Description
![11_User_Story_Routes](https://user-images.githubusercontent.com/90213877/158999586-4674c2d0-6472-4d12-b554-53ade2ecfda2.png)

## Acceptance Criteria
- [x] Routes Page opens by clicking on "Plan your Routes"
    - [x] if no Routes are planned "No Routes planned yet" should show as a text
- [x] RouteCard shows "Route X", "Day X" and the date
- [x] By clicking the "go back" button the user gets back in browser history
 
## Tasks
- [x] Update Page / DetailPage
- [x] Create Page / DayPlaner
- [x] Create Component / DayCard
- [x] Check accessibility 
- [x] Add to App
    - [x] Update React Router 
- [x] Check UI on mobile phone
