### ISSUE TITLE
Add Detailpage for Routes

### ISSUE THREAD

**Issue by J-Massmann** [J-Massmann/capstone-project#21]
## Value Proposition
**As a** user
**I want to** see the details to each route
**in order to** have a better overview of my trip / route

## Description
![12_User_Story_Detailpage](https://user-images.githubusercontent.com/90213877/159018114-7d545fce-33ba-4b15-9851-e9ec7c1eb1fc.png)

## Acceptance Criteria
- [ ] By clicking on a single card, the user gets to its Detailpage
- [ ] On the Detailpage the locations are shown in an order
    - [ ] the user can change the order of the locations with the arrow on each locations (one rank up)
    - [ ] the first location doesn't have an arrow
    - [ ] the order is automatically saved
- [ ] By clicking the go back arrow, the user gets back in browser history  

## Tasks
- [ ] Create Page / DetailPageRoute
- [ ] Check accessibility 
- [ ] Add to App
   - [ ] Update React Router 
- [ ] Check UI on mobile phone
