### ISSUE TITLE
Edit-function for the routes

### ISSUE THREAD

**Issue by J-Massmann** [J-Massmann/capstone-project#22]
## Value Proposition
**As a** user
**I want to** be able to change my routes
**in order to** be more flexible in plan for my trip

## Description
![13_User_Story_Edit_Routes](https://user-images.githubusercontent.com/90213877/159022315-543c2e2f-5f66-4706-88fc-aa2ea4ac8f6c.png)

## Acceptance Criteria
- [ ] By clicking on the pencil button, the user gets to the Editpage
    - [ ] The user also gets to the Editpage by clicking the pencil-button on the Detailpage
- [ ] The User can change the date of the route and the including locations to the route
- [ ] By clicking the save-button the user gets back in the browser history
 
## Tasks
- [ ] Update Component/ RouteCard
- [ ] Update Page / Detailpage
- [ ] Create Page / EditPage
- [ ] Check accessibility 
- [ ] Add to App
    - [ ] Update React Router
- [ ] Check UI on mobile phone
