### ISSUE TITLE
Delete-function for the routes

### ISSUE THREAD

**Issue by J-Massmann** [J-Massmann/capstone-project#23]
## Value Proposition
**As a** user
**I want to** be able to delete a route
**in order to** be more flexible in planing my trip / routes

## Description
![14_User_Story_Delete_Routes](https://user-images.githubusercontent.com/90213877/159028111-e0a13e3c-a527-4080-8f09-97757822c210.png)

## Acceptance Criteria
- [ ] Delete alert message will appear by clicking the Bin-Button
- [ ] Trip will be deleted if 'Yes' is clicked
   - [ ] User will be navigated back in browser history
- [ ] User will stay on the page if "No" is clicked 

## Tasks
- [ ] Update Page/ EditPage
- [ ] Check accessibility 
- [ ] Add to App
- [ ] Check UI on mobile phone
