### ISSUE TITLE
Custom error message for form element

### ISSUE THREAD

**Issue by J-Massmann** [J-Massmann/capstone-project#5]
## Value Proposition
**As a** admin
**I want to** throw an error, if required input aren't filled out
**in order to** a correctly working app

## Description
<img width="500" src="https://user-images.githubusercontent.com/90213877/156643882-4cf5724a-770d-4df9-ae7c-df61cf829648.png" />

## Acceptance Criteria
- [ ] The destination input is required
   - [ ] error-message when focus goes away from input and is not filled
   - [ ] error-message will disappear as soon as the input field is filled out (min 1 character)

## Tasks
- [ ] Create component/ErrorDestination
   - [ ] Test
   - [ ] Storybook
- [ ] Check accessibility
- [ ] Check UI on mobile phone
